# Generated by Django 4.2.3 on 2023-07-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teklif', '0002_alter_teklif_insaat_alter_teklif_nakliye_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teklif',
            name='cekvade',
            field=models.IntegerField(choices=[(30, 30), (60, 60), (90, 90)], default=60),
        ),
        migrations.AlterField(
            model_name='teklif',
            name='indikator',
            field=models.CharField(choices=[('ABS-B3', 'ABS-B3'), ('ABS-I1', 'ABS-I1')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='teklif',
            name='usmodel',
            field=models.CharField(choices=[('B', 'B'), ('C', 'C'), ('CB', 'CB'), ('CC', 'CC'), ('V', 'V'), ('I', 'I')], default=1, max_length=5),
        ),
        migrations.AlterField(
            model_name='teklif',
            name='yazar',
            field=models.CharField(choices=[('Erhan ATALAN', 'Erhan ATALAN'), ('Serdar BULUT', 'Serdar BULUT'), ('Davut ATALAN', 'Davut ATALAN')], default=1, max_length=100),
        ),
    ]
