# Generated by Django 4.2.3 on 2023-07-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teklif', '0004_alter_teklif_insaat_alter_teklif_nakliye_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teklif',
            name='indikator',
            field=models.CharField(choices=[('ABS-B3', 'ABS-B3'), ('ABS-I1', 'ABS-I1')], default='X', max_length=10),
        ),
        migrations.AlterField(
            model_name='teklif',
            name='insaat',
            field=models.CharField(choices=[('ALICI FIRMA TARAFINDAN', 'Alıcı Firma Tarafından'), ('SATICI FIRMA TARAFINDAN', 'Satıcı Firma Tarafından')], default='A', max_length=100),
        ),
        migrations.AlterField(
            model_name='teklif',
            name='nakliye',
            field=models.CharField(choices=[('ALICI FIRMA TARAFINDAN', 'Alıcı Firma Tarafından'), ('SATICI FIRMA TARAFINDAN', 'Satıcı Firma Tarafından')], default='A', max_length=100),
        ),
        migrations.AlterField(
            model_name='teklif',
            name='usmodel',
            field=models.CharField(choices=[('B', 'B'), ('C', 'C'), ('CB', 'CB'), ('CC', 'CC'), ('V', 'V'), ('I', 'I')], default='B', max_length=5),
        ),
        migrations.AlterField(
            model_name='teklif',
            name='vinc',
            field=models.CharField(choices=[('ALICI FIRMA TARAFINDAN', 'Alıcı Firma Tarafından'), ('SATICI FIRMA TARAFINDAN', 'Satıcı Firma Tarafından')], default='A', max_length=100),
        ),
        migrations.AlterField(
            model_name='teklif',
            name='yazar',
            field=models.CharField(choices=[('Erhan ATALAN', 'Erhan ATALAN'), ('Serdar BULUT', 'Serdar BULUT'), ('Davut ATALAN', 'Davut ATALAN')], default='Q', max_length=100),
        ),
    ]
