# Generated by Django 4.2.3 on 2023-07-21 12:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teklif', '0005_alter_teklif_indikator_alter_teklif_insaat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teklif',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teklif',
            name='indikator',
            field=models.CharField(choices=[('ABS-B3', 'ABS-B3'), ('ABS-I1', 'ABS-I1')], max_length=10),
        ),
        migrations.AlterField(
            model_name='teklif',
            name='insaat',
            field=models.CharField(choices=[('ALICI FIRMA TARAFINDAN', 'Alıcı Firma Tarafından'), ('SATICI FIRMA TARAFINDAN', 'Satıcı Firma Tarafından')], max_length=100),
        ),
        migrations.AlterField(
            model_name='teklif',
            name='nakliye',
            field=models.CharField(choices=[('ALICI FIRMA TARAFINDAN', 'Alıcı Firma Tarafından'), ('SATICI FIRMA TARAFINDAN', 'Satıcı Firma Tarafından')], max_length=100),
        ),
        migrations.AlterField(
            model_name='teklif',
            name='usmodel',
            field=models.CharField(choices=[('B', 'B'), ('C', 'C'), ('CB', 'CB'), ('CC', 'CC'), ('V', 'V'), ('I', 'I')], max_length=5),
        ),
        migrations.AlterField(
            model_name='teklif',
            name='vinc',
            field=models.CharField(choices=[('ALICI FIRMA TARAFINDAN', 'Alıcı Firma Tarafından'), ('SATICI FIRMA TARAFINDAN', 'Satıcı Firma Tarafından')], max_length=100),
        ),
        migrations.AlterField(
            model_name='teklif',
            name='yazar',
            field=models.CharField(choices=[('Erhan ATALAN', 'Erhan ATALAN'), ('Serdar BULUT', 'Serdar BULUT'), ('Davut ATALAN', 'Davut ATALAN')], max_length=100),
        ),
    ]
